# Dev Services - Quarkus sobe o Postgres automático se o Docker estiver aberto
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update

# Ativa o OpenTelemetry para enviar dados ao Jaeger
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.sdk.disabled=false